export const computers = [
  {
    id: '1',
    name: 'LENOVO YOGA',
    image: 'images/cmp1.jpg',
    price: '4450',
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    id: '2',
    name: 'HP laptop',
    image: 'images/cmp1.jpg',
    price: '4000',
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    id: '3',
    name: 'LG new laptop',
    image: 'images/cmp1.jpg',
    price: '1950',
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    id: '4',
    name: 'Samsong pro',
    image: 'images/cmp1.jpg',
    price: '2750',
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    id: '5',
    name: 'Lenovo pro',
    image: 'images/cmp1.jpg',
    price: '14000',
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    id: '6',
    name: 'Toshiba pro',
    image: 'images/cmp1.jpg',
    price: '2100',
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
  {
    id: '7',
    name: 'Apple pro',
    image: 'images/cmp1.jpg',
    price: '8100',
    detail: {
      CPUmodel: 'i7',
      hardDiskSize: '512',
      computerMemorySize: '8',
      screenSize: '13',
      operatingSystem: 'Windows 10 Home',
    },
  },
];
